### ISSUE TITLE
Explore S3 bucket for available data

### ISSUE THREAD

**Issue by kumar-rohini** [NeuroHackademy2024/neuro-nav#2]
- determine what neuroimaging data derivatives are available via the S3 bucket
- decide which to visualize on the dashboard

**Comment by kumar-rohini** [comment]
Here is the path to the open-neurodata bucket on the S3 cloud server that contains data derivatives from HCP:

s3://open-neurodata/hcp1200/

This folder contains subject folders with the following structure:

- s3://open-neurodata/hcp1200/sub-XXXXXX/
  - ses-1/
    - anat/
      - preproc/
      - registered/
    - connectomes/
      - [lots of files here]
    - dwi/
      - fiber/
      - preproc/
    - qa/
      - graphs_plotting/
      - reg/
      - skull_strip/
      - tensor/

**Comment by kumar-rohini** [comment]
If we want quick access to a csv with processed data to explore from one subject, we can look here:

s3://open-neurodata/rokem/hcp1200/afq/tract_profiles.csv

The afq/ folder also contains individual subject folders for subjects from HCP 1200 with tractometry data.

Each subject's individual data is located here:
s3://open-neurodata/rokem/hcp1200/afq/sub-XXXXXX/ses-01/sub-XXXXXX_dwi_space-RASMM_model-CSD_desc-prob-afq_profiles.csv

**Comment by arokem** [comment]
> s3://open-neurodata/rokem/hcp1200/afq/tract_profiles.csv

Just a warning that this file contains the data from all 1200 subjects. There are also (much!) smaller CSV files in the individual subject folders that are alongside this file.
