### ISSUE TITLE
Load CSV option

### ISSUE THREAD

**Issue by smehdizadeh** [NeuroHackademy2024/neuro-nav#7]
Add a button on the website that allows a user to load a CSV with data that they have stored locally, so that they may explore that data. For example, if they have access to the HCP demographic/behavioural data and have stored that somewhere, then they can specify the path to that CSV file and be able to explore it on the app. That way, we can still develop the functionality for viewing that data, but we do not have to worry about uploading the data to GitHub or something.

**Comment by jonathanwehnert** [comment]
this seems to work via

``````
from ipywidgets import FileUpload
import io
import pandas as pd

# Create a file upload widget
upload = FileUpload(accept='.csv', multiple=False)

# Display the file upload widget
display(upload)

# make separate cell to update after user has uploaded something:
test = upload.value[0].content
test2 = io.BytesIO(test)
df2 = pd.read_csv(test2)
df2.head()
```````````

**Comment by smehdizadeh** [comment]
Working on implementing this solution! Will clean up and push

**Comment by smehdizadeh** [comment]
The main issue we have been having with this is that our File Loader class needs to be able to communicate with all of our interactive plotter classes. That way the plotters know when the data have been loaded. 

I want to try implementing this as an "observer method" (abstract?) structure. From first glance, it seems like this might solve this issue, but I'm not familiar with this structure at all. If anyone has suggestions please share!!

Ex:
https://www.geeksforgeeks.org/observer-method-python-design-patterns/

**Comment by smehdizadeh** [comment]
Observer method works. The other key thing to getting this working was to make sure we were updating the attributes of existing widgets in the class and not just re-instantiating new widgets (for example, existing_widget_name.options = new_options)

**Comment by smehdizadeh** [comment]
File load is working on notebook but not on web browser. Good enough....
